BookAnArtisanMVC/BookAnArtisanMVC/Controllers/MeetingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookAnArtisanMVC.MeetingServiceReference;

namespace BookAnArtisanMVC.Controllers
{
    public class MeetingsController : Controller
    {
        MeetingServiceClient pCl = new MeetingServiceClient();

        // GET: Project
        public ActionResult Index()
        {
            try
            {
                var data = pCl.ReadAll();
                pCl.Close();
                return View(data);
            }
            catch (Exception e)
            {
                pCl.Abort();
                return new HttpStatusCodeResult(404, e.Message);
            }

        }

        public ActionResult Details(Meeting meeting)
        {
            try
            {
                var data = pCl.Read(meeting);
                pCl.Close();
                return View(data);
            }
            catch (Exception)
            {
                pCl.Abort();
                throw;
            }
        }

        public ActionResult Create()
        {
            return View();
        }

        // POST: Meeting/Create
        [HttpPost]
        public ActionResult Create(Meeting meeting)
        {
            try
            {
                // TODO: Add insert logic here
                meeting.CreatedById = "2083af25-f483-4a02-a62b-71c198147c84";
                pCl.Create(meeting);
                return RedirectToAction("MyMeetings");
            }
            catch
            {
                return View(meeting);
            }
        }

        // GET: Meeting/Edit/5
        public ActionResult Edit(Meeting meeting)
        {
            try
            {
                var data = pCl.Read(meeting);
                pCl.Close();
                return View(data);
            }
            catch (Exception)
            {
                pCl.Abort();
                throw;
            }
        }

        // POST: Meeting/Edit/5
        [HttpPost, ActionName("Edit")]
        public ActionResult EditConfirmed(Meeting meeting)
        {
            try
            {
                pCl.Update(meeting);
                return RedirectToAction("MyMeetings"); 
            }
            catch
            {
                return View(meeting);
            }
        }

        // GET: Meeting/Delete/5
        public ActionResult Delete(Meeting meeting)
        {
            try
            {
                var data = pCl.Read(meeting);
                pCl.Close();
                return View(data);
            }
            catch (Exception)
            {
                pCl.Abort();
                throw;
            }
        }

        // POST: Meeting/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(Meeting meeting)
        {
            try
            {
                pCl.Delete(meeting);
                return RedirectToAction("MyMeetings");
            }
            catch
            {
                return View(meeting);
            }
        }

        public ActionResult MyMeetings(User Iguess)
        {
            Iguess.Id = "2083af25-f483-4a02-a62b-71c198147c84";
            var data = pCl.ReadAllForUser(Iguess);
            return View(data);
        }
    }
}

BookAnArtisanMVC/BookAnArtisanMVC/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookAnArtisanMVC.ProjectServiceReference;

namespace BookAnArtisanMVC.Controllers
{
    public class ProjectsController : Controller
    {
        ProjectServiceClient pCl = new ProjectServiceClient();

        // GET: Project
        public ActionResult Index()
        {
            try
            {
                var data = pCl.ReadAll();
                pCl.Close();
                return View(data);
            }
            catch (Exception)
            {
                pCl.Abort();
                return View("NoResponseFromServer");
                //return new HttpStatusCodeResult(404, "Item Not Found");
            }
            
        }

        public ActionResult Details(Project project)
        {
            try
            {
                var data = pCl.Read(project);
                pCl.Close();
                return View(data);
            }
            catch (Exception)
            {
                pCl.Abort();
                throw;
            }
        }

        public ActionResult Create()
        {
            return View();
        }

        // POST: Project/Create
        [HttpPost]
        public ActionResult Create(Project project)
        {
            try
            {
                // TODO: Add insert logic here
                pCl.Create(project);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(project);
            }
        }

        // GET: Project/Edit/5
        public ActionResult Edit(Project project)
        {
            try
            {
                var data = pCl.Read(project);
                pCl.Close();
                return View(data);
            }
            catch (Exception)
            {
                pCl.Abort();
                throw;
            }
        }

        // POST: Project/Edit/5
        [HttpPost, ActionName("Edit")]
        public ActionResult EditConfirmed(Project project)
        {
            try
            {
                // TODO: Add update logic here
                pCl.Update(project);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(project);
            }
        }

        // GET: Project/Delete/5
        public ActionResult Delete(Project project)
        {
            try
            {
                var data = pCl.Read(project);
                pCl.Close();
                return View(data);
            }
            catch (Exception)
            {
                pCl.Abort();
                throw;
            }
        }

        // POST: Project/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(Project project)
        {
            try
            {
                pCl.Delete(project);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(project);
            }
        }
    }
}

BookAnArtisanMVC/BookAnArtisanMVC/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookAnArtisanMVC.UserServiceReference;

namespace BookAnArtisanMVC.Controllers
{

    public class UsersController : Controller
    {
        UserServiceClient uCl = new UserServiceClient();

        public ActionResult Index()
        {
            return View(uCl.ReadAll());
        }

        public ActionResult Edit(User user)
        {
            return View(uCl.Read(user));
        }

        [HttpPost, ActionName("Edit")]
        public ActionResult EditConfirmed(User user)
        {
            return View(uCl.Update(user));
        }

        public ActionResult Delete(User user)
        {
            return View(uCl.Read(user));
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(User user)
        {
            uCl.Delete(user);
            return RedirectToAction("Index");
        }


        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(User user)
        {
            if (ModelState.IsValid)
            {
                uCl.Create(user);

                return RedirectToAction("Index");
            }
            else
            {
                return View(user);
            }


        }

        public ActionResult Details(User user)
        {
            return View(uCl.Read(user));
        }

        [HttpPost]
        public JsonResult SearchByName(string name)
       {
            return Json(uCl.SearchByName(name), JsonRequestBehavior.AllowGet);
        }
    }
}

BookAnArtisanMVC/BookAnArtisanMVC/Views/Shared/NoResponseFromServer.cshtml
@{
    ViewBag.Title = "NoResponseFromServer";
}

<h2>Could not connect to service or server. No response.</h2>

BookAnArtisanMVC/BookAnArtisanMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/jqueryui")
    @RenderSection("styles", required: false)
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css"> 

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Apacta", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Projekter", "Index", "Projects")</li>
                    <li>@Html.ActionLink("Brugere", "Index", "Users")</li>
                    <li>@Html.ActionLink("Møder", "Index", "Meetings")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Mine Møder", "MyMeetings", "Meetings")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Book An Artisan</p>
        </footer>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script> 
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)




</body>
</html>